/** IDs del shell de cartilla — un mapa por módulo para evitar conflictos en DOM/CSS. */

export const PMPAR_SHELL_IDS = {
  app: "pmparApp",
  fileInput: "pmpar-file-input",
  fileWrap: "pmpar-file-wrap",
  runReview: "pmpar-run-review",
  reviewAll: "pmpar-review-all",
  exportErrors: "pmpar-export-errors",
  clear: "pmpar-clear",
  exportFiltered: "pmpar-export-filtered",
  inspectionDate: "pmpar-inspection-date",
  harvestDate: "pmpar-harvest-date",
  resultsHeader: "pmpar-results-header",
  resultsBody: "pmpar-results-body",
  resultsTable: "pmpar-results-table",
  resumenTodas: "pmpar-resumen-todas",
  resultsSection: "pmpar-results-section",
  totalFilas: "pmpar-total-filas",
  resultsTitle: "pmpar-results-title",
  resultsSubtitle: "pmpar-results-subtitle",
  resultsIcon: "pmpar-results-icon",
  reviewStats: "pmpar-review-stats",
  liveBadge: "pmpar-live-badge",
  liveLabel: "pmpar-live-label",
  excelInsight: "pmpar-excel-insight",
  colMenu: "pmpar-col-menu"
};

export const AGV_MP_SHELL_IDS = {
  app: "agvMpApp",
  fileInput: "agv-mp-file-input",
  fileWrap: "agv-mp-file-wrap",
  runReview: "agv-mp-run-review",
  reviewAll: "agv-mp-review-all",
  exportErrors: "agv-mp-export-errors",
  clear: "agv-mp-clear",
  exportFiltered: "agv-mp-export-filtered",
  inspectionDate: "agv-mp-inspection-date",
  inspectionType: "agv-mp-inspection-type",
  lmrDate: "agv-mp-lmr-date",
  harvestDate: "agv-mp-harvest-date",
  resultsHeader: "agv-mp-results-header",
  resultsBody: "agv-mp-results-body",
  resultsTable: "agv-mp-results-table",
  resumenTodas: "agv-mp-resumen-todas",
  resultsSection: "agv-mp-results-section",
  totalFilas: "agv-mp-total-filas",
  resultsTitle: "agv-mp-results-title",
  resultsSubtitle: "agv-mp-results-subtitle",
  resultsIcon: "agv-mp-results-icon",
  reviewStats: "agv-mp-review-stats",
  liveBadge: "agv-mp-live-badge",
  liveLabel: "agv-mp-live-label",
  excelInsight: "agv-mp-excel-insight",
  notificationIcon: "agv-mp-notification-icon",
  notificationCount: "agv-mp-notification-count",
  colMenu: "agv-mp-col-menu"
};

export const AGV_PT_SHELL_IDS = {
  app: "agvPtApp",
  fileInput: "agv-pt-file-input",
  fileWrap: "agv-pt-file-wrap",
  runReview: "agv-pt-run-review",
  clear: "agv-pt-clear",
  exportFiltered: "agv-pt-export-filtered",
  inspectionDate: "agv-pt-inspection-date",
  packagingDate: "agv-pt-packaging-date",
  harvestDate: "agv-pt-harvest-date",
  inspectionType: "agv-pt-inspection-type",
  lmrDate: "agv-pt-lmr-date",
  resultsHeader: "agv-pt-results-header",
  resultsBody: "agv-pt-results-body",
  resultsTable: "agv-pt-results-table",
  resultsSection: "agv-pt-results-section",
  totalFilas: "agv-pt-total-filas",
  resultsTitle: "agv-pt-results-title",
  resultsSubtitle: "agv-pt-results-subtitle",
  liveBadge: "agv-pt-live-badge",
  liveLabel: "agv-pt-live-label",
  excelInsight: "agv-pt-excel-insight",
  tableSearchWrap: "agv-pt-table-search-wrap",
  tableSearch: "agv-pt-table-search",
  tableWrap: "agv-pt-table-wrap",
  colMenu: "agv-pt-col-menu"
};
